% Clear workspace and command window
clear all;
clc;

% Define objective function (energy cost)
function energy_cost = objective_function(x)
    % Define energy cost function
    cost_per_kwh = 2;     % Cost per kWh(assuming 2 dollars,in paper it is high as it is considered penalty)
    energy_generated = 0.1 * x(1);     % Energy generated by PV system (kWh)x(1) and x(2) are decision variables
    energy_stored = x(2) / 1000;    % Energy stored in BESS system (kWh)
    energy_consumed = energy_generated - energy_stored;    % Energy consumed (kWh)
    energy_cost = cost_per_kwh * energy_consumed;    % Energy cost ($)
end

n = 2;                      % Number of variables
lb = [0, 0];                % Lower bounds
ub = [500, 2000];           % Upper bounds

% Define PSO parameters and run the algorithm
options = optimoptions('particleswarm', 'SwarmSize', 50, 'MaxIterations', 100);
[x, fval] = particleswarm(@objective_function, n, lb, ub, options);

% Results
fprintf('Optimized PV power: %.2f W\n', x(1));
fprintf('Optimized BESS capacity: %.2f Wh\n', x(2));
fprintf('Minimum energy cost: $%.2f\n', fval);
